# Used to get the type of the token
NUMBER, NEWLINE, OPERATOR, EOF, UNKNOWN,ADD, SUBTRACT,\
MULTIPLY, DIVIDE, LEFT_PAREN, RIGHT_PAREN = ( 'NUMBER', 'NEWLINE', 'OPERATOR', 'EOF', 'UNKNOWN',
    'ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'LEFT_PAREN', 'RIGHT_PAREN')


